// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqmtgxwbnxflbttbbbba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbXRneHdibnhmbGJ0dGJiYmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODc2NDgsImV4cCI6MjA2Njk2MzY0OH0.4GkMXynH7x5_rpm0FZuKOlMhw_PvjGrE0gkr_hRCUGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});